name: GRSON
description: Free Flutter App Template created by Creative Tim.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  flutter_svg:
  carousel_slider:
  firebase_core:
  firebase_auth:
  scrollable_positioned_list:
  cloud_firestore:
  firebase_storage:
  image_picker:
  url_launcher:
  get:
  get_storage:
  http:
  firebase_messaging:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images_welcomepages/
    - assets/icons_welcomepages/
    - assets/img_secondpages/
    - assets/img_secondpages/pro-background.png
    - assets/img_secondpages/onboard-background.png
    - assets/img_secondpages/logo-android.png
    - assets/img_secondpages/logo-ios.png
    - assets/img_secondpages/logo-argon.png
    - assets/img_secondpages/profile-screen-avatar.jpg
    - assets/img_secondpages/profile-screen-bg.png
    - assets/img_secondpages/register-bg.png
    - assets/img_secondpages/chat-avatar.jpeg
    - assets/img_secondpages/argon-logo.png
    - assets/img_secondpages/argon-logo-onboarding.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts_secondpages/OpenSans-Regular.ttf
        - asset: assets/fonts_secondpages/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts_secondpages/OpenSans-Bold.ttf
          weight: 600

